require("dotenv").config();

PORT = process.env.PORT || 8080;
NODE_ENV = process.env.NODE_ENV || "development";

DB_URL = process.env.DB_URL;
DEV_DB_NAME = process.env.DEV_DB_NAME;
PROD_DB_NAME = process.env.PROD_DB_NAME;

JWT_PRIVATE_KEY = process.env.JWT_PRIVATE_KEY;

EMAIL_HOST = process.env.EMAIL_HOST;
EMAIL_PORT = process.env.EMAIL_PORT;
EMAIL_USER = process.env.EMAIL_USER;
EMAIL_PASSWORD = process.env.EMAIL_PASSWORD;

GOOGLE_CLIENT_EMAIL = process.env.GOOGLE_CLIENT_EMAIL;
GOOGLE_PRIVATE_KEY = process.env.GOOGLE_PRIVATE_KEY;

GOOGLE_PRIVATE_KEY = GOOGLE_PRIVATE_KEY.replace(/\\n/g, "\n");

STUDENTS_SHEET_ID = process.env.STUDENTS_SHEET_ID;
CURRICULUM_SHEET_ID = process.env.CURRICULUM_SHEET_ID;
ATTENDANCE_SHEET_ID = process.env.ATTENDANCE_SHEET_ID;
CLASSES_SHEET_ID = process.env.CLASSES_SHEET_ID;
CC_SHEET_ID = process.env.CC_SHEET_ID;
MENTORS_SHEET_ID = process.env.MENTORS_SHEET_ID;
TE_SEMINARS_SHEET_ID = process.env.TE_SEMINARS_SHEET_ID;
BE_PROJECTS_SHEET_ID = process.env.BE_PROJECTS_SHEET_ID;
HONORS_SHEET_ID = process.env.HONORS_SHEET_ID;

VALID_ATTENDANCE = process.env.VALID_ATTENDANCE;
VALID_UT_MARKS = process.env.VALID_UT_MARKS;

VALID_ATTENDANCE = VALID_ATTENDANCE ? parseFloat(VALID_ATTENDANCE) : 75;
VALID_UT_MARKS = VALID_UT_MARKS ? parseFloat(VALID_UT_MARKS) : 12;

module.exports = {
  PORT,
  NODE_ENV,
  DB_URL,
  DEV_DB_NAME,
  PROD_DB_NAME,
  JWT_PRIVATE_KEY,
  EMAIL_HOST,
  EMAIL_PORT,
  EMAIL_USER,
  EMAIL_PASSWORD,
  GOOGLE_CLIENT_EMAIL,
  GOOGLE_PRIVATE_KEY,
  STUDENTS_SHEET_ID,
  CURRICULUM_SHEET_ID,
  ATTENDANCE_SHEET_ID,
  CLASSES_SHEET_ID,
  CC_SHEET_ID,
  MENTORS_SHEET_ID,
  TE_SEMINARS_SHEET_ID,
  BE_PROJECTS_SHEET_ID,
  HONORS_SHEET_ID,
  VALID_ATTENDANCE,
  VALID_UT_MARKS,
};
